# This is a reusable workflow for creating an issue

name: create-failure-issue

# Controls when the workflow will run

on:
  # Allows you to run this workflow from another workflow
  
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body: 
        required: true
        type: string

  # Allows you to call this manually from the Actions tab
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue title'
        required: true
      body:
        description: 'Issue body'
        required: true
        

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This bug is open for 30 days with any activity. It will be closed in 5 days'
        days-before-stale: 30
        days-before-close: 5
