# This is a reusable workflow for creating an issue

name: create-failure-issue

# Controls when the workflow will run

on:
  # Allows you to run this workflow from another workflow
  
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body: 
        required: true
        type: string

  # Allows you to call this manually from the Actions tab
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue title'
        required: true
      body:
        description: 'Issue body'
        required: true
        

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello job2" > test.txt 
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: cat test.txt
