name: CI - Test Action

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        uses: lgmorand/github-action-hello@v1
        with:
          firstname: 'louis-guillaume'
